FROM node:22.22.1-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 4200
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--proxy-config", "proxy.conf.json", "--poll", "1000"]
