services:
  frontend:
    container_name: mb-filmstack-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "8067:80"
    depends_on:
      - backend

  backend:
    container_name: mb-filmstack-backend
    build:
      context: ./backend
      dockerfile: pocketbase.Dockerfile
    restart: unless-stopped
    ports:
      - "8068:8090"
    env_file:
      - .env
    volumes:
      - pb_data:/pb_data
      - ./backend/pb_migrations:/pb_migrations
      - ./backend/pb_hooks:/pb_hooks

volumes:
  pb_data:
